name: Prepare
description: Prepares the repo for a CI job

inputs:
  node-version:
    required: false
    description: "`node-version` passed to `actions/setup-node`."
    default: 18.17.0

runs:
  using: "composite"
  steps:
    - name: Configure Git
      run: |
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name ${GITHUB_ACTOR}
      shell: bash
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: "latest"
    - run: bun install
      shell: bash
